<?php if ($block->getData('posts')):
    $type = $block->getDetail();

    if ($type == 1) {
        ?>
		    <h1 class='posts'><?php echo $block->getData('posts'); ?></h1>
	            <h2><?php echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('Type_two')
            ->toHtml(); ?>
		<?php
    }
    if ($type == 0) {
        ?>
		    <h1 class='posts'><?php echo $block->getData('posts'); ?></h1>
	            <h2><?php echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('Type_one')
            ->toHtml(); ?>

		<?php
    }
    ?>
		<?php endif;?>
