<div class="field confirmation required">
    <label for="type-confirmation" class="label"><span><?=$block->escapeHtml(__('Type'))?></span></label>
        <select name="type" id="type">
            <option value="none" selected disabled hidden>Select the Type</option>
            <option value="Type One">Type One</option>
            <option value="Type Two">Type Two</option>
        </select>
</div>
